# @package _group_

stock_performance:
  monthly: True
  weekly: True
  overall: True

profit_loss_history: True

trading_history: True

yield_rate:
  my_portfolio: True
  dia: True
  ixic: True
  spy: True

net_liquidity: True

current_holding: True
